FORMAT: 1A
HOST: http://private-7723ff-octolog.apiary-mock.com/

# OctoLog

OCTOLog is a simple API to easily generate beautiful CV and bio.

## User details [/people/{trigram}/basics]

### Update user details [PUT]

+ Parameters
    + trigram: `JBI` (String, required) - ID of the person

+ Request (application/json)

        {
            "firstName": "Billy",
            "lastName": "Joe",
            "pictureUrl": "https://pbs.twimg.com/profile_images/456738286732455936/uJGJyDbl.jpeg",
            "job": "Architect",
            "education":["UTC (Technical University of Compiegne)", "City University of Hong Kong"],
            "skills":{
                "technical": ["platform/frameworks: node, iOS, Rails, J2EE, Play", "Devops: Ansible, Puppet, Capistrano"],
                "architectureTechnologies": ["Architecture studies", "Audits", "API Design"],
                "methodologies": ["Agile", "Lean", "Lean Startup"],
                "achievements": ["Speaker", "Blog articles"]
            }
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "firstName": "Billy",
            "lastName": "Joe",
            "trigram": "JBI",
            "pictureUrl": "https://pbs.twimg.com/profile_images/456738286732455936/uJGJyDbl.jpeg",
            "job": "Architect",
            "education":["UTC (Technical University of Compiegne)", "City University of Hong Kong"],
            "skills":{
                "technical": ["platform/frameworks: node, iOS, Rails, J2EE, Play", "Devops: Ansible, Puppet, Capistrano"],
                "architectureTechnologies": ["Architecture studies", "Audits", "API Design"],
                "methodologies": ["Agile", "Lean", "Lean Startup"],
                "achievements": ["Speaker", "Blog articles"]
            }
        }


### Get user details [GET]

+ Parameters
    + trigram: `JBI` (String, required) - ID of the person

+ Response 200 (application/json; charset=utf-8)


        {
            "firstName": "Billy",
            "lastName": "Joe",
            "trigram": "JBI",
            "pictureUrl": "https://pbs.twimg.com/profile_images/456738286732455936/uJGJyDbl.jpeg",
            "job": "Architect",
            "education":["UTC (Technical University of Compiegne)", "City University of Hong Kong"],
            "skills":{
                "technical": ["platform/frameworks: node, iOS, Rails, J2EE, Play", "Devops: Ansible, Puppet, Capistrano"],
                "architectureTechnologies": ["Architecture studies", "Audits", "API Design"],
                "methodologies": ["Agile", "Lean", "Lean Startup"],
                "achievements": ["Speaker", "Blog articles"]
            }
        }

### Delete user details [DELETE]

+ Parameters
    + trigram: `JBI` (String, required) - ID of the person

+ Response 200 (application/json; charset=utf-8)


## Experience details [/experiences/{id}]


### Update an Experience [PUT]

You may update an experience to add details.

+ Parameters
    + id: `3000003189` (String, required) - ID of the experience

+ Request (application/json)

        {
            "mission": "R2016-877 - ING DIRECT AUSTRALIA - AGILE TEAM",
            "projectId": 123456,
            "customer":"Pacifica",
            "role":"Developer 1",
            "from": "2015-08-05T08:40:51.620Z",
            "to": "2015-08-05T08:40:51.620Z",
            "description": [
                "Frame internal API product",
                "Design solution and push up technology choices",
                "Develop solution"
            ],
            "tags": ["agile", "javascript"]
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "id": "3000003189",
            "projectId": 123456,
            "mission": "R2016-877 - ING DIRECT AUSTRALIA - AGILE TEAM",
            "customer":"Pacifica",
            "role":"",
            "from": "2015-08-05",
            "to": "2015-08-05",
            "description": [
                "Frame internal API product",
                "Design solution and push up technology choices",
                "Develop solution"
            ],
            "tags": ["agile", "javascript"]
        }

### Get an Experience [GET]

You may retrieve an experience to add details.

+ Parameters
    + id: `123456` (Number, required) - ID of the experience

+ Response 200 (application/json; charset=utf-8)

        {
            "id": "123456",
            "projectId": 123456,
            "mission": "R2016-877 - ING DIRECT AUSTRALIA - AGILE TEAM",
            "customer":"ING Direct Australia",
            "role":"Developer 1",
            "from": "2015-08-05",
            "to": "2015-08-05",
            "description": [
                "Frame internal API product",
                "Design solution and push up technology choices",
                "Develop solution"
            ],
            "tags": ["agile", "javascript"]
        }

## Experiences Collection [/people/{trigram}/experiences]

+ Parameters
    + trigram: `JBI` (String, required) - ID of the person

### Add an Experience [POST]

You may add a new experience

+ Request (application/json)

        {
            "id": "1234568",
            "projectId": 123456,
            "mission": "R2016-877 - ING DIRECT AUSTRALIA - AGILE TEAM",
            "customer":"ING Direct Australia",
            "role":"Developer 1",
            "from": "2015-08-05T08:40:51.620Z",
            "to": "2015-08-05T08:40:51.620Z",
            "description": [
                "Frame internal API product",
                "Design solution and push up technology choices",
                "Develop solution"
            ],
            "tags": ["agile", "javascript"]
        }

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "id": "1234568",
                "projectId": 123456,
                "mission": "R2016-877 - ING DIRECT AUSTRALIA - AGILE TEAM",
                "customer":"ING Direct Australia",
                "role":"Developer 1",
                "from": "2015-08-05",
                "to": "2015-08-05",
                "description": [
                    "Frame internal API product",
                    "Design solution and push up technology choices",
                    "Develop solution"
                ],
                "tags": ["agile", "javascript"]
            }


### List All Past Experiences [GET]

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "id": "123456",
                "projectId": 123456,
                "mission": "R2016-877 - ING DIRECT AUSTRALIA - AGILE TEAM",
                "customer":"ING Direct Australia",
                "role":"Developer 1",
                "from": "2015-09-23",
                "to": "2015-11-14",
                "description": [
                    "Frame internal API product",
                    "Design solution and push up technology choices",
                    "Develop solution"
                ],
                "tags": ["agile", "javascript"]
            },
            {
                "id": "1234567",
                "projectId": 123456,
                "mission": "AUTRE MISSION",
                "customer":"Australian Post",
                "role":"Architect",
                "from": "2015-09-23",
                "to": "2015-11-14",
                "description": [
                    "Frame internal API product",
                    "Design solution and push up technology choices",
                    "Develop solution"
                ],
                "tags": ["agile", "javascript"]
            }
        ]

### Delete user details [DELETE]

+ Parameters
    + id: `123456` (String, required) - ID of the person

+ Response 200 (application/json; charset=utf-8)

## Octopod [/people/{id}/octopod/sync]

+ Parameters
    + id: `JBI` (String, required) - ID of the person

### Sync [POST]

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "id": "123456",
                "projectId": 123456,
                "mission": "R2016-877 - ING DIRECT AUSTRALIA - AGILE TEAM",
                "customer":"ING Direct Australia",
                "role":"Developer 1",
                "from": "Aug 2015",
                "to": "Nov 2015",
                "description": [
                    "Frame internal API product",
                    "Design solution and push up technology choices",
                    "Develop solution"
                ],
                "tags": ["agile", "javascript"]
            },
            {
                "id": "3000003189",
                "projectId": 2146900417,
                "mission": "Refonte Neptune",
                "customer": "Pacifica",
                "role": "Shadowing"
            }
        ]

## ASKBOB [/people/{id}/askbob/sync]

+ Parameters
    + id: `JBI` (String, required) - ID of the person

### Sync [POST]

+ Response 200 (application/json; charset=utf-8)

        {
          "job": "Consultant confirmed",
          "trigram": "TGE",
          "firstName": "Thibaut",
          "lastName": "Géry",
          "skills": {
            "fromAskbob": ["TDD (Test-Driven Development)"]
          }
        }
