FORMAT: 1A
HOST: http://private-7723ff-octolog.apiary-mock.com/

# OctoLog

OCTOLog is a simple API to easily generate beautiful CV and bio.

## User details [/people/{trigram}/cv/{name}]

### Update user details [PUT]

+ Parameters
    + trigram: `JBI` (String, required) - ID of the person
    + name: `default` (String, required) - name of the CV

+ Request (application/json)

        {
            "firstName": "Billy",
            "lastName": "Joe",
            "pictureUrl": "https://pbs.twimg.com/profile_images/456738286732455936/uJGJyDbl.jpeg",
            "job": "Architect",
            "education":["UTC (Technical University of Compiegne)", "City University of Hong Kong"],
            "skills":{
                "technical": ["platform/frameworks: node, iOS, Rails, J2EE, Play", "Devops: Ansible, Puppet, Capistrano"],
                "architectureTechnologies": ["Architecture studies", "Audits", "API Design"],
                "methodologies": ["Agile", "Lean", "Lean Startup"],
                "achievements": ["Speaker", "Blog articles"],
                "others": ["English", "Spanish"]
            }
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "firstName": "Billy",
            "lastName": "Joe",
            "trigram": "JBI",
            "name": "default",
            "pictureUrl": "https://pbs.twimg.com/profile_images/456738286732455936/uJGJyDbl.jpeg",
            "job": "Architect",
            "education":["UTC (Technical University of Compiegne)", "City University of Hong Kong"],
            "skills":{
                "technical": ["platform/frameworks: node, iOS, Rails, J2EE, Play", "Devops: Ansible, Puppet, Capistrano"],
                "architectureTechnologies": ["Architecture studies", "Audits", "API Design"],
                "methodologies": ["Agile", "Lean", "Lean Startup"],
                "achievements": ["Speaker", "Blog articles"],
                "others": ["English", "Spanish"]
            }
        }


### Get user details [GET]

+ Parameters
    + trigram: `JBI` (String, required) - ID of the person
    + name: `default` (String, required) - name of the CV

+ Response 200 (application/json)


        {
            "firstName": "Billy",
            "lastName": "Joe",
            "trigram": "JBI",
            "name": "default",
            "pictureUrl": "https://pbs.twimg.com/profile_images/456738286732455936/uJGJyDbl.jpeg",
            "job": "Architect",
            "education":["UTC (Technical University of Compiegne)", "City University of Hong Kong"],
            "skills":{
                "technical": ["platform/frameworks: node, iOS, Rails, J2EE, Play", "Devops: Ansible, Puppet, Capistrano"],
                "architectureTechnologies": ["Architecture studies", "Audits", "API Design"],
                "methodologies": ["Agile", "Lean", "Lean Startup"],
                "achievements": ["Speaker", "Blog articles"],
                "others": ["English", "Spanish"]
            }
        }



## Experience details [/people/{trigram}/experiences/{id}]


### Update an Experience [PUT]

You may update an experience to add details.

+ Parameters
    + id: `3000003189` (String, required) - ID of the experience
    + trigram: `JBI` (String, required) - ID of the person

+ Request (application/json)

        {
            "mission": "R2016-877 - ING DIRECT AUSTRALIA - AGILE TEAM",
            "octopodProjectId": 123456,
            "customer":"Pacifica",
            "customerLogo":"http://www.welcometothejungle.co/uploads/company/logo/octo-technology.png",
            "role":"Developer 1",
            "from": "2015-08-05T08:40:51.620Z",
            "to": "2015-08-05T08:40:51.620Z",
            "description": [
                "Frame internal API product",
                "Design solution and push up technology choices",
                "Develop solution"
            ],
            "tags": ["agile", "javascript"]
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "id": "3000003189",
            "octopodProjectId": 123456,
            "trigram": "JBI",
            "mission": "R2016-877 - ING DIRECT AUSTRALIA - AGILE TEAM",
            "customer":"Pacifica",
            "customerLogo":"http://www.welcometothejungle.co/uploads/company/logo/octo-technology.png",
            "role":"",
            "from": "2015-08-05",
            "to": "2015-08-05",
            "description": [
                "Frame internal API product",
                "Design solution and push up technology choices",
                "Develop solution"
            ],
            "tags": ["agile", "javascript"]
        }

### Get an Experience [GET]

You may retrieve an experience to add details.

+ Parameters
    + id: `3000003189` (Number, required) - ID of the experience
    + trigram: `JBI` (String, required) - ID of the person

+ Response 200 (application/json; charset=utf-8)

        {
            "id": "123456",
            "octopodProjectId": 123456,
            "mission": "R2016-877 - ING DIRECT AUSTRALIA - AGILE TEAM",
            "customer":"ING Direct Australia",
            "customerLogo":"http://www.welcometothejungle.co/uploads/company/logo/octo-technology.png",
            "role":"Developer 1",
            "from": "2015-08-05",
            "to": "2015-08-05",
            "description": [
                "Frame internal API product",
                "Design solution and push up technology choices",
                "Develop solution"
            ],
            "tags": ["agile", "javascript"]
        }

### Delete an experience [DELETE]

+ Parameters
    + id: `3000003189` (Number, required) - ID of the experience
    + trigram: `JBI` (String, required) - ID of the person

+ Response 200 (application/json; charset=utf-8)

        {
            "id":"3000003189",
            "trigram":"JBI"
        }

## Experiences Collection [/people/{trigram}/cv/{name}/experiences]

+ Parameters
    + trigram: `JBI` (String, required) - ID of the person
    + name: `default` (String, required) - name of the CV

### Add an Experience [POST]

You may add a new experience

+ Request (application/json)

        {
            "id": "1234568",
            "octopodProjectId": 123456,
            "mission": "R2016-877 - ING DIRECT AUSTRALIA - AGILE TEAM",
            "customer":"ING Direct Australia",
            "customerLogo":"http://www.welcometothejungle.co/uploads/company/logo/octo-technology.png",
            "role":"Developer 1",
            "from": "2015-08-05T08:40:51.620Z",
            "to": "2015-08-05T08:40:51.620Z",
            "description": [
                "Frame internal API product",
                "Design solution and push up technology choices",
                "Develop solution"
            ],
            "tags": ["agile", "javascript"]
        }

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "id": "1234568",
                "octopodProjectId": 123456,
                "mission": "R2016-877 - ING DIRECT AUSTRALIA - AGILE TEAM",
                "customer":"ING Direct Australia",
                "customerLogo":"http://www.welcometothejungle.co/uploads/company/logo/octo-technology.png",
                "role":"Developer 1",
                "from": "2015-08-05",
                "to": "2015-08-05",
                "description": [
                    "Frame internal API product",
                    "Design solution and push up technology choices",
                    "Develop solution"
                ],
                "tags": ["agile", "javascript"]
            }


### List All Past Experiences [GET]

+ Response 200 (application/json; charset=utf-8)

        {"octo": [
            {
                "id": "123456",
                "octopodProjectId": 123456,
                "mission": "R2016-877 - ING DIRECT AUSTRALIA - AGILE TEAM",
                "customer":"ING Direct Australia",
                "customerLogo":"http://www.welcometothejungle.co/uploads/company/logo/octo-technology.png",
                "role":"Developer 1",
                "from": "2015-09-23",
                "to": "2015-11-14",
                "description": [
                    "Frame internal API product",
                    "Design solution and push up technology choices",
                    "Develop solution"
                ],
                "tags": ["agile", "javascript"]
            },
            {
                "id": "1234567",
                "octopodProjectId": 123456,
                "mission": "AUTRE MISSION",
                "customer":"Australian Post",
                "customerLogo":"http://www.welcometothejungle.co/uploads/company/logo/octo-technology.png",
                "role":"Architect",
                "from": "2015-09-23",
                "to": "2015-11-14",
                "description": [
                    "Frame internal API product",
                    "Design solution and push up technology choices",
                    "Develop solution"
                ],
                "tags": ["agile", "javascript"]
            }
        ],
        "priorToOcto": [
            {
                "id": "123456789",
                "customer":"Atari",
                "customerLogo":"http://www.welcometothejungle.co/uploads/company/logo/octo-technology.png",
                "role":"Intern",
                "from": "2008-09-23",
                "to": "2009-11-14",
                "description": [
                    "Improve coffee quality",
                    "Automate printer low ink alert",
                    "Develop closest sandwich shop application"
                ],
                "tags": ["C#"]
            }
        ]}


## Octopod [/people/{id}/cv/{name}/octopod/sync]

+ Parameters
    + id: `JBI` (String, required) - ID of the person
    + name: `default` (String, required) - name of the CV

### Sync [POST]

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "id": "3000003189",
                "trigram": "JBI",
                "octopodProjectId": 2146900417,
                "mission": "Refonte Neptune",
                "customer": "Pacifica",
                "from":"2013-11-15",
                "to":"2013-11-15",
                "tags": [],
                "description": [],
                "role": "Shadowing",
                "customerLogo": null
            }
        ]

## ASKBOB [/people/{id}/cv/{name}/askbob/sync]

+ Parameters
    + id: `JBI` (String, required) - ID of the person
    + name: `default` (String, required) - name of the CV

### Sync [POST]

+ Response 200 (application/json; charset=utf-8)

        {
          "job": "Consultant confirmed",
          "trigram": "TGE",
          "firstName": "Thibaut",
          "lastName": "Géry",
          "name": "default",
          "pictureUrl": "http://s3.amazonaws.com/askbob/users/photos/312/preview/CINE1232.jpg?1476667003",
          "skills": {
            "technical": [],
            "architectureTechnologies": [],
            "methodologies": [],
            "achievements": [],
            "others": ["TDD (Test-Driven Development)"]
          }
        }
